name: Auto Release

on:
  push:
    branches:
      - main  # or 'master' if your branch is named that

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Get package version
        id: version
        run: |
          version=$(node -p "require('./package.json').version")
          echo "VERSION=$version" >> $GITHUB_OUTPUT

      - name: Commit & Push tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git tag "v${{ steps.version.outputs.VERSION }}"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }} --tags
