name: Release - Auto Tag

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Bump version and push tag
        env:
          PAT: ${{ secrets.GH_PAT }}
        run: |
          version=$(node -p "require('./package.json').version")
          git tag "v$version"
          git push https://x-access-token:${PAT}@github.com/${{ github.repository }} --tags