name: Push tag to repository
env:
    GH_PAT: ${{ secrets.GH_PAT }}
run: |
    git config user.name "github-actions[bot]"
    git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
    git tag $VERSION
    git remote set-url origin https://x-access-token:${GH_PAT}@github.com/ayushsinghtech/my-blog-practice.git
    git push origin $VERSION
