name: Release Version

on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - name: Debug GH_PAT
        run: echo "${{ secrets.GH_PAT }}" # **Remove this after debugging**

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check remote URL
        run: git remote -v

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Get version from package.json
        id: get_version
        run: |
          echo "VERSION=v$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - name: Set up Git and push tag
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
    
          echo "Current remotes before change:"
          git remote -v

          # Set remote URL with PAT token
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/ayushsinghtech/my-blog-practice.git

          echo "Current remotes after change:"
          git remote -v

          # Check authentication by listing remote branches
          git ls-remote origin

          # Create tag if it doesn't exist
          if git rev-parse "$VERSION" >/dev/null 2>&1; then
            echo "Tag $VERSION already exists locally."
          else
            git tag $VERSION
            echo "Tag $VERSION created."
          fi

          # Push tag to origin
          git push origin $VERSION --force

          echo "Tag pushed successfully."
