name: Release - Auto Tag

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Read version from package.json and create tag
        id: tag
        run: |
          version=$(node -p "require('./package.json').version")
          echo "version=v$version" >> $GITHUB_OUTPUT

      - name: Push tag
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git tag ${{ steps.tag.outputs.version }}
          git push https://x-access-token:${GH_PAT}@github.com/${{ github.repository }} ${{ steps.tag.outputs.version }}
